### ISSUE TITLE
D3

### ISSUE THREAD

**Issue by moklick** [efekarakus/d3-peaks#9]
Hey,
I was wondering why this package has "d3" in its name. Is it somehow related to d3.js?

**Comment by efekarakus** [comment]
Hi Moritz,

Yes, that was the original intent! I wanted to follow Mike Bostock's ["Let's make a D3 plugin"](https://bost.ocks.org/mike/d3-plugin/) article while building this library.
So although it doesn't have any d3 dependencies atm, I think it can be thought of similarly to the [d3-array](https://github.com/d3/d3-array) module. I tried to follow a similar pattern of coding.

[Here is an example](http://bl.ocks.org/efekarakus/cc7303456841523f37dd) of using it with d3js.

**Comment by moklick** [comment]
that was fast ;) I am maintaining a [list with d3 plugins](https://github.com/wbkd/awesome-d3). That's why I am asking. I will put it under "utils". Even if it is not directly related to d3 there are a lot of use cases to use it with d3.

**Comment by efekarakus** [comment]
Thanks! I'll close the issue now if that's okay :)

**Comment by moklick** [comment]
sure. Thanks :+1:
